import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "", 
    default: "This is the title of the root layout.tsx", 
    template: "%s | child template"
  },
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: 'lightblue', padding: '1rem' }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: 'ghostwhite', padding: '1rem' }}>
          Footer
        </footer>
      </body>
    </html>
  );
}
